// <auto-generated />
using System;
using Mensajeria.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mensajeria.API.Migrations
{
    [DbContext(typeof(MensajeriaAPIContext))]
    [Migration("20260324060844_V04")]
    partial class V04
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mensajeria.Modelos.Conversacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha_Creacion_Conversacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Tipo_Conversacion")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo_Conversacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Conversacion");
                });

            modelBuilder.Entity("Mensajeria.Modelos.EstadoMensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion_Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadoMensaje");
                });

            modelBuilder.Entity("Mensajeria.Modelos.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido_Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConversacionId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Hora_Envio_Mensaje")
                        .HasColumnType("time without time zone");

                    b.Property<int>("RemitenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId");

                    b.HasIndex("RemitenteId");

                    b.ToTable("Mensaje");
                });

            modelBuilder.Entity("Mensajeria.Modelos.MensajeLectura", b =>
                {
                    b.Property<int>("MensajeId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoMensajeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha_Lectura")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MensajeId", "UsuarioId");

                    b.HasIndex("EstadoMensajeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MensajeLectura");
                });

            modelBuilder.Entity("Mensajeria.Modelos.ParticipanteConversacion", b =>
                {
                    b.Property<int>("ConversacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha_Ingreso_Participante")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ConversacionId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ParticipanteConversacion");
                });

            modelBuilder.Entity("Mensajeria.Modelos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre_Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Mensajeria.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena_Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo_Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado_Usuario")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha_Creacion_Usuario")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre_Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Mensajeria.Modelos.Mensaje", b =>
                {
                    b.HasOne("Mensajeria.Modelos.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mensajeria.Modelos.Usuario", "Remitente")
                        .WithMany()
                        .HasForeignKey("RemitenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");

                    b.Navigation("Remitente");
                });

            modelBuilder.Entity("Mensajeria.Modelos.MensajeLectura", b =>
                {
                    b.HasOne("Mensajeria.Modelos.EstadoMensaje", "EstadoMensaje")
                        .WithMany()
                        .HasForeignKey("EstadoMensajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mensajeria.Modelos.Mensaje", "Mensaje")
                        .WithMany()
                        .HasForeignKey("MensajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mensajeria.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoMensaje");

                    b.Navigation("Mensaje");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mensajeria.Modelos.ParticipanteConversacion", b =>
                {
                    b.HasOne("Mensajeria.Modelos.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mensajeria.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mensajeria.Modelos.Usuario", b =>
                {
                    b.HasOne("Mensajeria.Modelos.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
